### ISSUE TITLE
[bug] FediverseTextBlur.user.js の @match におけるtypo?

### ISSUE THREAD

**Issue by hanubeki** [hidao80/UserScript#8]
**Target UserScript name**\
**対象となるUserScriptの名前**
FediverseTextBlur.user.js

**Describe the bug** A clear and concise description of what the bug is.\
**バグを説明する** バグが何であるかを明確かつ簡潔に説明します。
`// @match          https://vivaldi.social.net/*` とありますが、 `// @match          https://social.vivaldi.net/*` の間違いではないでしょうか。

**To Reproduce** Steps to reproduce the behavior:\
**再現させる方法** 動作を再現するための手順:
look at https://github.com/hidao80/UserScript/blob/main/src/FediverseTextBlur/FediverseTextBlur.user.js

**Expected behavior** A clear and concise description of what you expected to happen.\
**期待される動作** 期待される動作を簡潔明瞭に記述してください。
`@match` にて `https://social.vivaldi.net/*` が指定される

**Additional context** Add any other context about the problem here.\
**その他の状況** 問題に関するその他の状況をここに追加してください。
他のUserscriptではちゃんと `social.vivaldi.net` になっていました。

**Comment by hidao80** [comment]
@hanubeki バグレポートありがとうございます！ 👍 
早速修正しました。
今後もお気付きの点がありましたら、お気軽に Issue 立ててください。

ご確認の上、不具合が解決されているようでしたら本 Issue を Close してください。
1ヶ月以上応答がない場合はこちらで Close させていただきます。

**Comment by hanubeki** [comment]
このIssueにおける問題が修正されているのを確認したのでIssueを閉じます。
ありがとうございます。
